# Generated by Django 2.2.24 on 2022-04-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_schema__add_event_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='badgr_server_slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
