# Generated by Django 2.2.24 on 2022-04-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeclass',
            name='badgr_server_slug',
        ),
    ]
