# Generated by Django 2.2.24 on 2022-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_remove_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='badgr_server_slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
